services:
  kosync:
    build: .
    container_name: kosync
    restart: unless-stopped
    ports:
      - 7200:7200
    environment:
      - ENABLE_USER_REGISTRATION=true
      - ADMIN_PASSWORD=change-me
    volumes:
      - /mnt/cache/appdata/koreader-sync-server/test/logs/app:/app/koreader-sync-server/logs
      - /mnt/cache/appdata/koreader-sync-server/test/logs/redis:/var/log/redis
      - /mnt/cache/appdata/koreader-sync-server/test/data/redis:/var/lib/redis
